#!/usr/bin/env bash
# installs and configures HAProxy on load balancer server
# enable a dedicated PPA with following commands:
# sudo apt-get install software-properties-common
# sudo add-apt-repository ppa:vbernat/haproxy-1.8
# then install HAProxy
sudo apt-get update
sudo apt-get -y install haproxy=1.8.\*
# enable HAProxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
# tutorial did this:
# sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
# distribute requests
config="\nfrontend web-frontend\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\toption forwardfor\n\tmode http\n\tserver 539-web-01 35.227.63.107:80 check\n\tserver 539-web-02 35.243.218.35:80 check\n\n"
echo -e $config | sudo tee -a /etc/haproxy/haproxy.cfg
# reload and restart HAProxy
sudo service haproxy reload
sudo service haproxy restart
