#!/usr/bin/env bash
# creates a file /var/run/holbertonscript.pid containing its PID
# displays "To infinity and beyond" indefinitely
# displays "I hate the kill command" when receiving a SIGTERM signal
# displays "Y U no love me?!" when receiving a SIGINT signal
# deletes the file /var/run/holbertonscript.pid and terminates itself when
# receive SIGQUIT signal
filen="/var/run/holbertonscript.pid"
selfpid="$(pgrep -f '100-process_and_pid_file')"
touch $filen
echo "$selfpid" > $filen
i=1
while [ $i -eq 1 ]
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I hate the kill command"; rm -f $filen; kill $$' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'rm -f $filen; kill $$' SIGQUIT
done
