#!/usr/bin/env bash
# creates a file /var/run/holbertonscript.pid containing its PID
# displays "To infinity and beyond" indefinitely
# displays "I hate the kill command" when receiving a SIGTERM signal
# displays "Y U no love me?!" when receiving a SIGINT signal
# deletes the file /var/run/holbertonscript.pid and terminates itself when
# receive SIGQUIT signal
filen="/var/run/holbertonscript.pid"
sudo touch $filen
echo $$ > $filen
i=1
while [ $i -eq 1 ]
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I hate the kill command"; sudo rm $filen' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'sudo rm $filen' SIGQUIT
done
