#!/usr/bin/env bash
# this bash script displays numbers from 1 to 100
# displays "FizzBuzz" when number is multiple of 3 and 5
# displays "Fizz" when number is multiple of 3
# displays "Buzz" when number is multiple of 5
for ((i = 1; i <= 100; i++))
do
    if (( i % 15 == 0))
    then
        echo "FizzBuzz"
    elif (( i % 5 == 0 ))
    then
        echo "Buzz"
    elif (( i % 3 == 0 ))
    then
        echo "Fizz"
    else
        echo "$i"
    fi
done
