#!/usr/bin/env bash
# this script displays numbers from 1 to 20
# displays 4 and then "bad luck from China" for 4th iteration
# displays 9 and then "bad luck from Japan" for 9th iteration
# displays 17 and then "bad luck from Italy" for 17th iteration
i=1
while [ $i -le 20 ]
do
    echo "$i"
    if [ $i -eq 4 ]
    then
        echo "bad luck from China"
    elif [ $i -eq 9 ]
    then
        echo "bad luck from Japan"
    elif [ $i -eq 17 ]
    then
        echo "bad luck from Italy"
    fi
        (( i++ ))
done
