#!/usr/bin/env bash
# this script displays content of current directory in list format where
# only the part of the name after the first dash is displayed
LIST="$(ls)"
for name in $LIST
do
    echo "$name" | cut -d "-" -f 2
done
