#!/usr/bin/env bash
# this script gives you information about the holbertonschool file
file1="holbertonschool"
if [ -e "$file1" ]
then
    echo "holbertonschool file exists"
    if [ -s "$file1" ]
    then
        echo "holbertonschool file is not empty"
    else
        echo "holbertonschool file is empty"
    fi
    if [ -f "$file1" ]
    then
        echo "holbertonschool file is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
