#!/usr/bin/env bash
# transfers a file from our client to my server
pathtofile="$1"
ipaddr="$2"
username="$3"
pathsshkey="$4"
if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$pathsshkey" "$pathtofile" "$username"@"$ipaddr":~/
fi
