#!/usr/bin/env bash
# installs nginx web server, nginx listen on port 80
findstr="/location / {"
insertstr="location /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4\n}"
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School for the win!" | sudo tee /usr/share/nginx/html/index.html
sudo sed "$findstr/i $insertstr" /etc/nginx/sites-enabled/default
sudo service nginx start
