#!/usr/bin/env bash
# installs nginx web server, nginx listen on port 80
insertstr="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
errstr="\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
sudo apt-get update
sudo apt-get -y install nginx
echo -e "Holberton School for the win!\n" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "37a\ $insertstr" /etc/nginx/sites-enabled/default
sudo sed -i "37a\ $errstr" /etc/nginx/sites-enabled/default
echo -e "Ceci n'est pas une page\n" | sudo tee /usr/share/nginx/html/custom_404.html
sudo service nginx start
