#!/usr/bin/env bash
# makes localhost resolve to 127.0.0.2 and facebook.com resolve to 8.8.8.8
old="127.0.0.1 localhost"
new="127.0.0.2 localhost"
cp /etc/hosts ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
sed -i "s/$old/$new/g" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
